// The SpillArena account, vendored into every game. See types.ts.
export * from './types'
export * from './session'
export * from './api'
export * from './sync'
export * from './progress'
export * from './identity'
export * from './username-policy'
export * from './consent'
export { detectLanguage } from './language'
export { useConsent } from './useConsent'
export { ConsentDialog } from './ConsentDialog'
export type { ConsentDialogProps, ConsentItem } from './ConsentDialog'
export { useAccount } from './useAccount'
export { AccountBadge } from './AccountBadge'
export type { AccountBadgeLabels, AccountBadgeProps } from './AccountBadge'
